package try_catch;

public class Ex4 {

	public static void main(String[] args) {
		
		
		
		try {
			
			int num1 = 3;
			int num2 = 0;
			
			System.out.println(num1 / num2);
			
		} catch (Exception e) {
//			e.printStackTrace();
			System.out.println(e.getMessage());
		}
		
		
		
		
		
		
		
		
		
		
	}

}
